### ISSUE TITLE
Data management: Lighten "placeholder" text on manage environments page

### ISSUE THREAD

**Issue by alechenninger** [lightblue-platform/lightblue-applications#70]
This is a browser default style, but for whatever reason it's easy to mistake for actual text in the input fields.

Unfortunately there is no standardized `::placeholder` pseudo-selector, but various browsers have implemented prefixed support.

We need some css rules like this:

```css
::-webkit-input-placeholder {
   color: lightgray;
}

::-moz-placeholder {
   color: lightgray;  
}

:-ms-input-placeholder {  
   color: lightgray;  
}
```
